import "../styles/globals.css";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { RouteProvider } from "./_components/route-provider";
import { TRPCReactProvider } from "./_components/trpc-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} antialiased scroll-smooth`}
      data-scroll-behavior="smooth"
    >
      <body>
        <TRPCReactProvider>
          <RouteProvider>{children}</RouteProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
