import "../styles/globals.css";

import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "sonner";

import { HydrateClient } from "@/lib/trpc-server";

import { RouteProvider } from "./_components/route-provider";
import { TRPCReactProvider } from "./_components/trpc-provider";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const viewport: Viewport = {
  colorScheme: "light",
};

export const metadata: Metadata = {
  title: "Use Next Ship",
  description: "Generated by use-next-ship",
  authors: [{ name: "Danilo Martinelli" }],
  creator: "@danilomartinelli",
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} antialiased scroll-smooth`}
      data-scroll-behavior="smooth"
    >
      <body>
        <TRPCReactProvider>
          <RouteProvider>
            <HydrateClient>{children}</HydrateClient>
            <Toaster />
          </RouteProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
